Add aggregates meta tags
positiondev/offset pull request #62
Opened 2018-10-25 15:45 UTC by emhoracek

2018-10-26 18:27 UTC, dhartunian requested changes

2018-10-26 18:27 UTC, dhartunian commented on spec/Common.hs
> +toWPResp (body, headers) = return $ Right $ WPResponse headers body
it's confusing to see `(body, headers)` followed by `headers body` on the right hand side. I think standardizing on an order across the codebase is valuable. I would suggest headers and then body since that's the order the request has them from top to bottom.

2018-10-26 18:27 UTC, dhartunian commented on spec/Main.hs
> +deadTests = do
this name is because...?

2018-10-26 18:27 UTC, dhartunian commented on spec/Main.hs
> +                                          (enc (WPResponse mempty (enc [a2])))
worth having a helper for a response with no headers?

2018-10-26 18:27 UTC, dhartunian commented on src/Web/Offset/Cache.hs
> +                 do resp <- wpRequest wpKey
I'm imagining putting this in production and it retrieving a key from an older cached WP request that has no headers. Where will it fail to decode into a WPResponse and what will happen? We should either have a plan to explicitly clear the cache when we deploy this or be backwards compatible w/r/t the payloads already cached in Redis.

2018-10-26 18:29 UTC, emhoracek commented on spec/Main.hs
> +deadTests = do
There's a `liveTests` that is tests of a live server. I'll change the name XD

2018-10-26 18:30 UTC, emhoracek commented on spec/Main.hs
> +                                          (enc (WPResponse mempty (enc [a2])))
yeah that might make the test set up simpler

ugh these tests are so weird I really want to refactor them complete..... resisting....

2018-10-26 18:32 UTC, emhoracek commented on src/Web/Offset/Cache.hs
> +                 do resp <- wpRequest wpKey
Ooh, good thinking. I can add a fallback in the `ToJSON` implementation to avoid that.

2018-10-26 18:35 UTC, emhoracek commented on spec/Common.hs
> +toWPResp (body, headers) = return $ Right $ WPResponse headers body
Yeah, originally it was just easier to paste `, mempty)` to the end of the line, but then I just made the `toWPResp` helper anyway. I should just make the helper add empty headers since they're empty for most of the tests.

2018-10-29 18:11 UTC, emhoracek commented on src/Web/Offset/Cache.hs
> +                 do resp <- wpRequest wpKey
I meant `FromJSON` above. Added a fallback. It turns out you can write things like ` v .:? "some_field" .!= "some default text"` which means, try to find some field, and if you can't find it, use this default.

2018-10-29 18:12 UTC, emhoracek commented
@dhartunian I used your suggestions -- take another look?

2018-10-29 20:50 UTC, merged